sudo: required
services:
  - docker

before_install:
  - docker build -t aerrick/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aerrick/react-test npm test

after_success:
  - docker build -t aerrick/multi-client ./client
  - docker build -t aerrick/multi-nginx ./nginx
  - docker build -t aerrick/multi-server ./server
  - docker build -t aerrick/multi-worker ./worker

# Docker login
  - echo "$DOCKER_PASSWORD | docker login -u" docker login -u "$DOCKER_ID" --password-stdin
# Push to docker hub
  - docker push aerrick/multi-client
  - docker push aerrick/multi-nginx
  - docker push aerrick/multi-server
  - docker push aerrick/multi-worker